---
# Architecture mapping
architecture: "{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}"

# Common packages configuration
common_install_packages: true
common_packages:
  - python3
  - python3-pip
  - git
  - curl
  - wget
  - vim
  - nano
  - bash-completion
  - net-tools
  - socat
  - conntrack
  - htop
  - tree
  - tmux
  - make
  - gcc
  - openssl
  - rsync
  - unzip
  - tar
  - gnupg2
  - ca-certificates
  - lsof
  - jq
  - gettext
  
common_pip_packages:
  - yamllint

# K8s tools configuration
install_kubectl: true
kubectl_version: "stable"

install_minikube: true

install_k8s_tools: true
stern_version: "1.28.0"
k9s_version: "0.31.9"
kubectx_version: "0.9.5"
kind_version: "0.22.0"
