---
- name: Download AWS CLI v2
  get_url:
    url: "https://awscli.amazonaws.com/awscli-exe-linux-{{ 'x86_64' if ansible_architecture == 'x86_64' else 'aarch64' }}.zip"
    dest: /tmp/awscliv2.zip

- name: Extract AWS CLI
  unarchive:
    src: /tmp/awscliv2.zip
    dest: /tmp
    remote_src: yes

- name: Install AWS CLI
  command: /tmp/aws/install --update
  args:
    creates: /usr/local/bin/aws

- name: Install AWS CLI completion
  shell: |
    aws_completer_path=$(which aws_completer)
    complete -C "$aws_completer_path" aws
    echo "complete -C \"$aws_completer_path\" aws" >> /etc/bash_completion.d/aws
  args:
    creates: /etc/bash_completion.d/aws
