---
galaxy_info:
  author: "Your Name"
  description: "Installs Jenkins with options for LTS or Weekly releases and specific versions"
  license: MIT
  min_ansible_version: 2.1

  # Provide a list of supported platforms, and for each platform a list of versions.
  platforms:
    - name: Debian
      versions:
        - all
    - name: RedHat
      versions:
        - centos
        - rockylinux
        - almalinux
    - name: Fedora
      versions:
        - all

  # Optional: tags for the role to make it searchable in Galaxy
  galaxy_tags:
    - jenkins
    - ci
    - lts
    - weekly
    - automation

dependencies: []
