---
- name: Download ArgoCD CLI
  get_url:
    url: "https://github.com/argoproj/argo-cd/releases/download/v{{ argocd_version }}/argocd-linux-{{ architecture }}"
    dest: /usr/local/bin/argocd
    mode: '0755'
