---
- name: Download kustomize archive
  get_url:
    url: "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv{{ kustomize_version }}/kustomize_v{{ kustomize_version }}_linux_{{ architecture }}.tar.gz"
    dest: /tmp/kustomize.tar.gz

- name: Extract kustomize
  unarchive:
    src: /tmp/kustomize.tar.gz
    dest: /usr/local/bin
    remote_src: yes

- name: Set executable permission for kustomize
  file:
    path: /usr/local/bin/kustomize
    mode: '0755'
