- import_tasks: helm.yml
  when: install_helm | default(false)

- import_tasks: helmfile.yml
  when: install_helmfile | default(false)

- import_tasks: kustomize.yml
  when: install_kustomize | default(false)

- import_tasks: tilt.yml
  when: install_tilt | default(false)

- import_tasks: kluctl.yml
  when: install_kluctl | default(false)

- import_tasks: argocd.yml
  when: install_argocd | default(false)
