install_awscli: true
install_terraform: true
install_vault: true
install_helm: true
install_helmfile: true
install_kubectl: true
install_kustomize: true
install_k9s: true
install_tilt: true
install_stern: true
install_minikube: false
install_sonobuoy: false
install_ytt: false
install_kubeseal: true
install_sops: true
install_dive: true
install_lazydocker: true
install_hadolint: true
install_trivy: true
install_goss: false
install_checkov: false
install_molecule: false
install_testinfra: false
install_ansible_lint: true
install_common_packages: true
install_kluctl: true
install_argocd: true

# Architecture mapping
architecture: "{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}"

# GitOps tool versions
helm_version: "3.14.2"
helmfile_version: "0.162.0"
kluctl_version: "2.23.3"
kustomize_version: "5.3.0"
tilt_version: "0.33.11"
argocd_version: "2.10.1"

